### ISSUE TITLE
Inheritance & Boosters Issue

### ISSUE THREAD

**Issue by Koogle1000** [TheBusyBiscuit/QuickSell#1]
Hello,

I have been using QuickSell for a while. I run a decent prison server with 15-50 players on normally and have been having a few issues with Quicksell. Firstly, the pboosters do not always work. I have it set so when you vote you get a 2x monetary booster from GAListner however it only actually like 60% of the time. And then the other issue is inheritance is not working. I have it set so I rank's inheritance is A rank & at I mine you can't sell coal but at A rank you can, but then you try to sell coal to I mine and it doesn't work. And don't tell me to like restart the server or something I have tried multiple times. So if you know any solutions for these issues please let me know!

**Comment by MrEminent42** [comment]
Hi, are you still having these issues? I am working on bug fixes for this plugin over at [my fork](https://github.com/MrEminent42/QuickSell).

Unfortunately, I was unable to reproduce either of your issues. For your pBooster issue, could you try using a [different plugin to execute the commands](https://www.spigotmc.org/resources/votingplugin.15358/), and making sure they [have the correct syntax](https://dev.bukkit.org/projects/quicksell#title-4)? For your inheritance issue, please paste your config at hastebin.com. 

Also, what version of Spigot are you running?

**Comment by Koogle1000** [comment]
Hello, 

I am no longer having the inherentance issue, I fixed it soon after making the post. However I still have the booster issue. It is not an issue with GaListner because I have this issue irregardless is the plugin. I also am using the correct syntax, /pbooster monetary <player> 2 2. I am using PaparSpigot 1.8.8.

**Comment by MrEminent42** [comment]
Ah, that seems to be the problem. The syntax for boosters is `/[p]booster <type> <player> <multiplier> <duration>`. You have to include the player argument there so the plugin knows who to assign the booster to.

Try updating it to `/pbooster monetary {username} 2 2` as GAListener uses that `{username}` for the player name. Let me know if that syntax and let me know if that works!

**Comment by Koogle1000** [comment]
Sorry, I forgot to include that in there i do /pbooster monetary {username} 2 2. And also it always shows the message to the player like you have gotten a booster, but it only works 70% of the time.

**Comment by MrEminent42** [comment]
Hmm. Could you paste your GAListener config at hastebin.com? Also, if you see any errors regarding boosters when players vote in the console, please also paste them.

**Comment by Koogle1000** [comment]
https://pastebin.com/hgh7rGx1

There are no errors when players vote. This bug also occurs through other plugins though like when players get boosters in a crate.

**Comment by MrEminent42** [comment]
After some testing, I think I found the problem. Boosters are currently stored using the player's name, which is case sensitive. For your specific case, I think this could be the series of events leading to the pboosters not working:
* A user votes but doesn't capitalize his/her IGN
* GAListener issues the /pbooster command with the lowercase IGN
* The booster is activated, however is not activated for the proper player since the IGN is case sensitive

Another problem I found while looking at the code is that QuickSell boosters are not UUID-compatible; if a user changes his/her IGN then the booster will not apply to that person after they re-join the server. This is usually not a problem since boosters generally only last a few minutes or hours, however making boosters UUID-compatible will at the same time remove the case sensitivity. 

Since the author isn't updating the project anymore, I've [created a new issue on my fork](https://github.com/MrEminent42/QuickSell/issues/3). Let's use that issue for any further discussion.
